-- MySQL Script generated by MySQL Workbench
-- seg 13 mai 2019 10:36:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `SOBRENOME` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PUBLICACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PUBLICACAO` (
  `IMG_PUB` VARCHAR(45) NOT NULL,
  `DESC_PUB` VARCHAR(45) NOT NULL,
  `TITULO_PUB` VARCHAR(30) NOT NULL,
  `DATA_PUB` DATE NOT NULL,
  `PUB_PUB` VARCHAR(255) NOT NULL,
  `ID_PUB` INT NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID_PUB`),
  INDEX `fk_PUBLICACAO_USUARIO1_idx` (`USUARIO_ID` ASC),
  CONSTRAINT `fk_PUBLICACAO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `mydb`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMENTARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMENTARIO` (
  `ID_COM` INT NOT NULL AUTO_INCREMENT,
  `TEXTO` LONGTEXT NOT NULL,
  `DATA` DATE NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  `PUBLICACAO_ID_PUB` INT NOT NULL,
  PRIMARY KEY (`ID_COM`),
  INDEX `fk_COMENTARIO_USUARIO1_idx` (`USUARIO_ID` ASC),
  INDEX `fk_COMENTARIO_PUBLICACAO1_idx` (`PUBLICACAO_ID_PUB` ASC),
  CONSTRAINT `fk_COMENTARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `mydb`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMENTARIO_PUBLICACAO1`
    FOREIGN KEY (`PUBLICACAO_ID_PUB`)
    REFERENCES `mydb`.`PUBLICACAO` (`ID_PUB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
